remote_theme: poole/hyde

plugins:
  - jekyll-remote-theme

title:       AI-Copyright Reproducibility Harness
description: A reproducibility harness for LLM deployment testing across Azure AI Foundry and native APIs.
url:         https://ai-copyright-reproducibility.tauheed-elahee.com
baseurl:     ""

author:
  name: Tauheed Elahee
  url:  https://github.com/Tauheed-Elahee

github:
  repo: https://github.com/Tauheed-Elahee/AI-Copyright-Reproducibility
