
title:       AI Reproducibility
description: A reproducibility harness for LLM deployment testing across Azure AI Foundry and native APIs.
url:         https://ai-copyright-reproducibility.tauheed-elahee.com
baseurl:     ""

theme: just-the-docs

aux_links:
  GitHub:
    - https://github.com/Tauheed-Elahee/AI-Copyright-Reproducibility

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
